version: '3.8'
services:  
    php-52:
      container_name: php-52-apache
      network_mode: bridge
      build: 
          context: .
          dockerfile: Dockerfile
      volumes: 
          - ./src:/var/www/html
      ports: 
          - 8001:80
